### ISSUE TITLE
HONKERS 

### ISSUE THREAD

**Issue by IamCyBo** [BOSCH21ITA/Graphical_Programming#13]
When driving beside a nice lady the machine should reduce the speed of the vehicle to 30 km/h and honk <10 times> to ensure that she is aware of the situation. 

Test: Implement a “nice lady” and a “horn”. Place the nice lady on a test track and approach her at different speeds. Check the speed and the ten honks. Test it also with a not so nice lady to see if the speed doesn't reduce in this case. OPT: change the sound of the honk

**Comment by Frankybeen29** [comment]
Unnecessary issue deleted while processing issue #21
